Added "as_asgi()" in the web/apps/web_copo/routing.py file to fix the TypeError: __call__() missing 1 required positional argument: 'send' for Django channels